_meta:
  type: "internalusers"
  config_version: 2

admin:
  hash: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG"  # Admin123!@#456
  reserved: true
  backend_roles:
    - "admin"
  description: "Admin user"

tenant_x:
  hash: "$2a$12$PrpdgAEBMj9QvQUBCYhJBeBR.UgV7PP69KpbYs9d.PPQ/wgVkt19y"  # TenantX123!@#
  backend_roles:
    - "tenant_x_role"
  attributes:
    tenant: "x"

tenant_y:
  hash: "$2a$12$PoQXDf6xQB.O5AmzYNP9NuhNT.wGeucWoEp8K9z9K2bNgwERvw9Qu"  # TenantY123!@#
  backend_roles:
    - "tenant_y_role"
  attributes:
    tenant: "y"

tenant_z:
  hash: "$2a$12$WqZCh.ciJxUwqvD3R6Eve.QZz6IrXZFMqGcF8nqe.QUHswkUzXAFW"  # TenantZ123!@#
  backend_roles:
    - "tenant_z_role"
  attributes:
    tenant: "z"