# config/internal_users.yml
---
_meta:
  type: "internalusers"
  config_version: 2

# Admin user
admin:
  hash: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG"  # admin123
  reserved: true
  backend_roles:
    - "admin"
  description: "Admin user"

# Tenant X admin
tenant_x_admin:
  hash: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG"  # admin123
  backend_roles:
    - "tenant_x_admin"
  description: "Tenant X administrator"

# Tenant Y admin
tenant_y_admin:
  hash: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG"  # admin123
  backend_roles:
    - "tenant_y_admin"
  description: "Tenant Y administrator"

# Tenant Z admin
tenant_z_admin:
  hash: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG"  # admin123
  backend_roles:
    - "tenant_z_admin"
  description: "Tenant Z administrator"

