# config/roles_mapping.yml
---
_meta:
  type: "rolesmapping"
  config_version: 2

tenant_x_admin:
  users:
    - "tenant_x_admin"

tenant_y_admin:
  users:
    - "tenant_y_admin"

tenant_z_admin:
  users:
    - "tenant_z_admin"