_meta:
  type: "roles"
  config_version: 2

tenant_x_role:
  cluster_permissions:
    - "cluster_composite_ops_ro"
  index_permissions:
    - index_patterns:
        - "tenant-x-*"
      allowed_actions:
        - "crud"
        - "create_index"
        - "manage"

tenant_y_role:
  cluster_permissions:
    - "cluster_composite_ops_ro"
  index_permissions:
    - index_patterns:
        - "tenant-y-*"
      allowed_actions:
        - "crud"
        - "create_index"
        - "manage"

tenant_z_role:
  cluster_permissions:
    - "cluster_composite_ops_ro"
  index_permissions:
    - index_patterns:
        - "tenant-z-*"
      allowed_actions:
        - "crud"
        - "create_index"
        - "manage"