_meta:
  type: "rolesmapping"
  config_version: 2

tenant_x_role:
  users:
    - "tenant_x"
  backend_roles:
    - "tenant_x_role"

tenant_y_role:
  users:
    - "tenant_y"
  backend_roles:
    - "tenant_y_role"

tenant_z_role:
  users:
    - "tenant_z"
  backend_roles:
    - "tenant_z_role"